### ISSUE TITLE
OscServer is inaccessible due to its protection level (Unity 2017.1)

### ISSUE THREAD

**Issue by sergiobd** [keijiro/OscJack#12]
I'm getting the error:

"Assets/OscJack/Editor/OscMonitorWindow.cs(63,46): error CS0122: `OscJack.OscServer.ServerList.get' is inaccessible due to its protection level
"
In Unity 2017.2 . I dont get it in 2018.2.  Don't really understand why...

**Comment by keijiro** [comment]
OscJack now requires [assembly definition](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) support. So, it only works on 2017.3 or later.

Sorry for the misinformation. I updated README.
